### ISSUE TITLE
Display shows "Wifi not configured!". But Wifi is configured

### ISSUE THREAD

**Issue by ghost** [jamct/DoorsignEPD#2]
Hello,

I have now rebuilt the door sign. However, the display shows all the time "Wifi not configured! Connect to hotspot 'ESP32' and open 192.168.4.1" although I have connected to the hostpot, set up the wifi and set the server address (in my case both times http: // 192.168.178.26/server/?debug=true&display=7.5&content=door_sign&scale=28).

**Comment by jamct** [comment]
Hello,
which version of basecamp do you use? Please update to the current version.
You have to set "Server to load image from:" (IP or host name) and "Address to load image from:" (with "debug=false". E.g. `"/server/index.php?debug=false&display=7.5&content=door_sign&scale=28"`).

**Comment by JaquelineP** [comment]
Hi,

I had the same problem. Are you using the correct wifi library from the ESP? I got a message during compilation that there are multiple wifi.h libraries and arduino would use the default one. After I used the right wifi library the issue was solved.

**Comment by ghost** [comment]
IF the problem still exists, please report the -verbose utput of the Serial console...
