### ISSUE TITLE
ESP32 ruft nach deep sleep keine Grafik ab

### ISSUE THREAD

**Issue by rocklobster42195** [jamct/DoorsignEPD#24]
Hallo.
Der ESP ruft nach dem Aufwachen keine Grafik ab. Es erscheint im seriellen Monitor nur:
`.
.
.
.
.
.
Wait till the client is connected
Going to deep sleep now...
`
Selbst ein Aus- und wieder Einschalten, veranlasst den ESP32 nicht, die Grafik anzufordern.
Danke für die Hilfe.
Viele Grüße
Boris

**Comment by rocklobster42195** [comment]
M.E. fehlt da ein `tcpClientConnectionInProgress=true;` nach `Serial.println("Wait till the client is connected");` und die entsprechende Abfrage bevor der ESP32 schlafen gelegt wird.

**Comment by rocklobster42195** [comment]
Es ginge auch `while (!tcpClientConnected){}` nach `Serial.println("Wait till the client is connected");`

**Comment by jdede** [comment]
Moin, jupp. In Zeile 382 fehlt ein `tcpClientConnectionInProgress=true;`. `while (!tcpClientConnected){}` wäre busy-waiting und würde das async-Konzept zerstören. Hab gerade keine Hardware zum testen hier, werde das aber dann morgen oder am Montag testen und einen PR auf machen.

**Comment by D3viloper** [comment]
Guten Morgen, Ich habe das selbe Problem, Ich finde es jedoch sehr komisch, dass ich die Meldung "OnConnect" erst bekomme nachdem ich die Meldung "Going to deep sleep now" bekommen habe. (Den Code habe ich in Zeile 382 angepasst wie oben erwähnt.)

**Comment by rocklobster42195** [comment]
Denk daran, dass du in der Abfrage (Zeile 390) auch noch `|| tcpClientConnectionInProgress` ergänzt, wenn Du `tcpClientConnectionInProgress=true;` eingefügt hast.

**Comment by D3viloper** [comment]
Erstmals Danke für deine Hilfe,
Ich habe es noch hinzugefügt (Zeile 390) und es halt so halb funktioniert, jetzt habe ich das Problem das er nicht schlafen geht weil er angeblich nicht im Produktion Mode ist obwohl die Option aktiviert ist/wurde.

**Comment by rocklobster42195** [comment]
Probiere doch mal in der `index.php` des Servers die Zeile 3 einzubeziehen ("#" am Anfang löschen). Damit aktivierst du den "production mode" über den header.

**Comment by D3viloper** [comment]
Funktioniert jetzt alles, danke für die Hilfe!

**Comment by jdede** [comment]
Guten Abend,
so, habe einen PR erstellt. Das Problem tritt bei mir nun nicht mehr auf. Gibt es noch Kommentare oder Anmerkungen?

**Comment by rocklobster42195** [comment]
Danke. Bei mir ist alles gut.

**Comment by D3viloper** [comment]
Danke, bei mir ist auch alles gut
