### ISSUE TITLE
Seit PHP8 funktioniert der Server nicht mehr

### ISSUE THREAD

**Issue by dpuschek** [jamct/DoorsignEPD#41]
Hallo,
vor einem Jahr habe ich Debian nach Bookworm upgegraded. PHP hat sich dabei von Version 7.4 -> 8.2 aktualisiert. Seitdem funktioniert das Display nicht mehr.
Ich habe das Problem im Forum auf php.de geschildert, wo mir aber kaum geholfen wurde. Bin ich wirklich der letzte, der das EPaper-Display noch nutzt?

https://www.php.de/forum/webentwicklung/php-einsteiger/1611140-php-script-l%C3%A4uft-nach-systemupdate-nicht-mehr-uncaught-typeerror-imagedestroy

**Comment by smmmo** [comment]
Hi,

it's working for me with php 8.2.

Here's the output of the changes that I made (in 2022) to make it work again:
[git_diff.txt](https://github.com/user-attachments/files/17168995/git_diff.txt)

Hope that helps

**Comment by dpuschek** [comment]
thank you. I already did that changes, but it didn't solve the problem at all. I always get a black display with it. My black and white PNG file could no longer be converted correctly :(
With debug=true static_image.png is displayed correcly in the browser. But I got only a black eink display :(

**Comment by jdede** [comment]
Hey, cool: Someone is still using this code. Haven't touched it for quite a while but tried to fix the main PHP-issues (and I know again why I hate this language...) :-D

@dpuschek can you check the PR #42 and report if this works for you?

**Comment by dpuschek** [comment]
Thank you. Unfortunately I still got black images on the display. I attached both GET-requests and named it .png (otherwise I cannot attach binary files here - now I zipped both files). With debug=false I got just a 0xFF filled answer. 

[index.php.zip](https://github.com/user-attachments/files/17178302/index.php.zip)


Here are my apache logs for one request from the ESP32-Display:
access.log
192.168.1.112 - - [29/Sep/2024:08:50:51 +0200] "GET /server/index.php?debug=false&display=7.5&content=static_image&display=7.5 HTTP/1.1" 200 30938 "-" "-"

error.log
[Sun Sep 29 08:50:51.018955 2024] [php:warn] [pid 78161:tid 78161] [client 192.168.1.112:52455] PHP Warning:  Undefined array key "scale" in /home/wwwdir/server/index.php on line 63
[Sun Sep 29 08:50:51.073271 2024] [php:warn] [pid 78161:tid 78161] [client 192.168.1.112:52455] PHP Warning:  Undefined array key "red" in /home/wwwdir/server/index.php on line 131

**Comment by jdede** [comment]
Okay, just pushed another update to the PR. Can you please check again?

Weird: You are just having warnings in your `error.log`. There might be a problem in the binary representation for EPD or, more precisely, in the function `rawImage()`. To debug that, I have to first get one of the displays and an ESP in my fingers...

**Comment by dpuschek** [comment]
error.log warnings are gone! But still black display. Yes, the rawImage() function doen't work as it did in PHP7. I don't understand much about PHP, but there must changes at GDImage class at PHP8.

addition:
I solved my problem: 
I changed index.php:
$im = imagecreate($displayWidth, $displayHeight);
to
$im = imagecreatetruecolor($displayWidth, $displayHeight);

Now it works again!

**Comment by jdede** [comment]
Ah, good catch! Thanks! Updated the PR accordingly. There seems to be also an issue with the background color. Hope that the new version works. Can you please check it again? Afterwards, I can merge it into the main module.

**Comment by dpuschek** [comment]
New version work! But I'm only using 'static_image'. The other "contents" stuff I never used.

**Comment by jdede** [comment]
Okay, I briefly checked most of them. Should work. Lets see if someone complains after the merge.

Thanks for your support!

**Comment by smmmo** [comment]
> thank you. I already did that changes, but it didn't solve the problem at all.

So sorry, my mistake. My workaround in 2022 was to run the script inside a docker container with php8.1 and mount the directory of DoorsignEPD to use it inside the docker container. For this, the 2 fixes were enough.

However, thanks to @jdede for the proper fix!
