### ISSUE TITLE
entferne eraseDisplay

### ISSUE THREAD

**Issue by noxorius** [jamct/DoorsignEPD#7]
Hi
in der doorsignEPD.ino 
Zeile 166
Ich hab mich schon länger gefragt warum das display zuerst gelöscht werden muss und dann upgedatet.
wenn Du das eraseDisplay(true); mit einen delay(3000); ersetzt wird das display upgedatet ohne vorher gelöscht werden zu müssen.

Anscheinen hat der http client eine delay wenn Du ihn zu früh abfragst ist das Ergebnis leer --> kein Bild auf dem Display.

**Comment by JaquelineP** [comment]
Hi,

kann ich bestätigen. Funktioniert sehr gut und der Bildaufbau geht schneller.

**Comment by jamct** [comment]
Hallo,
werde ich testen und in den Code aufnehmen.
@noxorius Den HTTP-Client werde ich umstellen auf einen anderen Client mit Callbacks und auf das Ergeignis "Daten abgerufen" reagieren. Das ist die sauberere Lösung.

**Comment by MKdent** [comment]
Hallo,
bei mir wird,  nach dem Ersetzen von eraseDisplay(true) auf delay(3000), das Display einmal aktualisiert und bleibt dann aber auf weiß. Es wird kein neues Bild aufgebaut. Stimmt es nur den Befehl zu ersetzen?
Was in diesem Zusammenhang vielleicht passt: Wie oben beschrieben hat der http client ein Delay. Bei mir kommt es im Production Modus  vor, dass das Bild einige Male aktualisiert wird, dann aber nicht mehr. Laut Ausgabe im seriellen Monitor, erwacht zwar der esp32, aber es kommen keine Bild-Daten mehr an. Ich bekomme nur die Ausgabe "image loaded". Liegt das an meinem Server/Router. Hat jemand selbiges beobachtet?

**Comment by jamct** [comment]
@MKdent Das beschriebene Problem könnte damit zusammenhängen, dass die Daten nicht schnell genug angekommen sind (siehe oben). Ich arbeite da aktuell mit einem Delay, das werde ich ersetzen durch eine saubere Callback-Funktion (ausgelöst durch den erfolgreichen Download).
