### ISSUE TITLE
index.php contains carriage return

### ISSUE THREAD

**Issue by ghost** [jamct/DoorsignEPD#8]
Hi,
please remove ^M from the index.php located in the server folder. A closing php tag would be nice also ;)

raz0r

**Comment by jamct** [comment]
Where did you find ^M?

**Comment by ghost** [comment]
git clone source, open index.php on a linux machine

**Comment by ghost** [comment]
but this is not a major issue, as far as I can see the other php files are affected too.
Vim or Ed user are able to easily remove these carriage returns.

keep up the good work!

**Comment by jdede** [comment]
I believe this one can be closed as solved by #13
